# Generated by Django 3.0.5 on 2020-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.IntegerField()),
                ('details', models.TextField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
