# Generated by Django 3.0.5 on 2020-06-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfVariant', models.CharField(choices=[('ST', 'Standard'), ('MT', 'Metallic'), ('FL', 'Flocked'), ('GD', 'Glow In The Dark'), ('BW', 'Black and White'), ('PT', 'Patina'), ('OF', 'Outfits'), ('CW', 'Colorways'), ('PR', 'Proto')], default='ST', max_length=2)),
                ('nameOfVariant', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pop')),
            ],
        ),
    ]
