# Generated by Django 3.0.5 on 2020-06-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='nameOfVariant',
            new_name='name',
        ),
    ]
