# Generated by Django 3.0.5 on 2020-06-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200618_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Limited',
        ),
    ]
