# Generated by Django 3.0.5 on 2020-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200618_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='limited',
            name='typeOfVariant',
            field=models.CharField(choices=[('ST', 'Standard'), ('MT', 'Metallic'), ('FL', 'Flocked'), ('GD', 'Glow In The Dark'), ('BW', 'Black and White'), ('PT', 'Patina'), ('OF', 'Outfits'), ('CW', 'Colorways'), ('PR', 'Proto')], default='ST', max_length=2, verbose_name='Type of Variant'),
        ),
        migrations.AddField(
            model_name='pop',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
