# Generated by Django 3.0.5 on 2020-06-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200618_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
